title: Vishnupriya Rachakatla 
email: vishnupriya.rach2000@gmail.comlk
logo: assets/close_shot.png
description: <a href="https://https://www.linkedin.com/in/vishnupriya-rachakatla-762a21225/" target="_blank">  <img align="left" alt="Arjun | LinkedIn" width="30px"  src="assets/assets/IMG_4456.HEIC" />
show_downloads: true
theme: Jekyll-theme-Minimal
