title: Vishnupriya Rachakatla 
email: vishnupriya.rach2000@gmail.comlk
logo: assets/assets/closeshot.jpeg
description: <a href="https://https://www.linkedin.com/in/vishnupriya-rachakatla-762a21225/" target="_blank">  <img align="left" alt="Arjun | LinkedIn" width="30px"  src="assets/linkedin.png" />
show_downloads: true
theme: Jekyll-theme-Minimal
